Fixed broken/incorrect links
gordon-cs/gordon-360-ui pull request #1003
Opened 2021-02-18 04:19 UTC by josh-peters-2357

Went through whole readme and verified that each hyperlink goes to the correct destination.

2021-02-18 13:56 UTC, EjPlatzer requested changes
Thanks for looking through this! I think a couple of the links are not quite right, so I've suggested some changes.

2021-02-18 13:56 UTC, EjPlatzer commented on README.md
> +- [Stylelint](https://marketplace.visualstudio.com/items?itemName=glen-84.sass-lint) checks syntax correctness for Sass (`.scss` files)
```suggestion
- [Stylelint](https://marketplace.visualstudio.com/items?itemName=stylelint.vscode-stylelint) checks syntax correctness for Sass (`.scss` files)
```
We use stylelint, not sass-lint, for linting our `.scss` files.

2021-02-18 13:56 UTC, EjPlatzer commented on README.md
> +This project was bootstrapped with [Create React App](https://github.com/facebookincubator/create-react-app). Read the user guide [here](https://github.com/facebook/create-react-app/blob/master/packa
```suggestion
This project was bootstrapped with [Create React App](https://github.com/facebook/create-react-app). Read the user guide [here](https://github.com/facebook/create-react-app/blob/master/packages/cra-template/template/README.md).
```
We should fix both CRA links on this line.

2021-02-18 13:56 UTC, EjPlatzer commented on README.md
> +- After connecting to the virtual machine and setting up the backend, as documented in [gordon-360-api](https://github.com/gordon-cs/gordon-360-api/blob/develop/README.md#machines-and-sites),
```suggestion
- After connecting to the virtual machine and setting up the backend, as documented in [gordon-360-api](https://github.com/gordon-cs/gordon-360-api/blob/develop/README.md#running-the-api-locally),
```
I think this is where this link is meant to point to.

2021-02-23 21:20 UTC, josh-peters-2357 commented
Hey Evan! I made the suggested change. I rerequested review; I'm not sure if that's the right thing to do.

2021-02-23 21:20 UTC, EjPlatzer approved these changes
Looks great! Thanks for taking the time to check our links and fix everything up!

2021-02-23 21:49 UTC, merged