S21 Disable health pop-up but keep health tab #1228
gordon-cs/gordon-360-ui pull request #1234
Opened 2021-07-01 15:20 UTC by roddy3

Disable the health check popup from the home page, but leave the health tab unchanged. This way, nobody will be required to make a report in order to see the home page, but they can still report if needed.

<img width="484" alt="Screen Shot 2021-07-01 at 11 16 18 AM" src="https://user-images.githubusercontent.com/60272749/124149127-4a1b0d80-da5e-11eb-95a4-b8d85e38f674.png">

2021-07-01 15:59 UTC, silasw2 reviewed
Worked closely with this, someone else will have to approve. I think that it works fine, albeit a bit messy. But it is able to be undone if we need to in the future.

2021-07-01 16:11 UTC, Davideo37 requested changes
Wellness stuff LGTM, I would maybe add a comment that states why the code is left commented out, and what it does/how to undo it. Besides that you may want to pull develop into this branch before merge as there seems to be some outdated code in the Involvement Profile stuff.

2021-07-01 19:10 UTC, Davideo37 approved these changes
LGTM!

2021-07-01 19:51 UTC, Kevin-Chu58 reviewed
LGTM!

2021-07-02 14:11 UTC, mFelgate commented
I don’t recommend it at this point unless you are pretty comfortable with git, but 37 commits is a lot for one pull request and it would make following the changes rly hard. I would do a git reset head to remove all the commits. This will leave all the changes you made. Then I would go back and cherry pick changes and make 5 or 6 commits with descriptions for this PR.

2021-07-07 18:55 UTC, josh-peters-2357 submitted a review, later dismissed
lgtm

2021-07-09 14:49 UTC, roddy3 commented
> Not to prolong this further, but I am concerned with how easy this will be to track down in the future if we want to revert (though we could probably just revert this commit).
> Could we add a comment before each commented out section like this:
> `// @WELLNESS-CHECK disabled (following lines of commented code)`
> and maybe for large code blocks commented out add a `// END` line below so it's extra clear
-----------------

They were already instruction on how to revert it but I added more comment to it.

2021-07-09 19:44 UTC, merged