Added clickable Profile link to involvements roster
gordon-cs/gordon-360-ui pull request #1255
Opened 2021-07-07 20:43 UTC by Davideo37

Added a clickable name link to the involvements roster that routes to a member's public profile. Related to issue #1198, may solve said issue.

2021-07-08 12:10 UTC, josh-peters-2357 approved these changes
lgtm

2021-07-19 14:00 UTC, josh-peters-2357 requested changes

2021-07-19 14:00 UTC, josh-peters-2357 commented on src/views/InvolvementProfile/components/Membership/components/MemberList/components/MemberListSingle/index.js
> +      <Grid container alignItems="center" justify="space-evenly">
```suggestion
      <Grid container alignItems="center" justifyContent="space-evenly">
```

2021-07-19 14:00 UTC, josh-peters-2357 commented on src/views/InvolvementProfile/components/Membership/components/MemberList/components/MemberListSingle/index.js
> +        <Grid container alignItems="center" justify="flex-end" spacing={3}>
```suggestion
        <Grid container alignItems="center" justifyContent="flex-end" spacing={3}>
```

2021-07-19 14:04 UTC, roddy3 requested changes

2021-07-19 14:04 UTC, roddy3 commented on src/views/InvolvementProfile/components/Membership/components/MemberList/components/MemberListSingle/index.js
> +            <Link className="gc360-link" to={`/profile/${member.AD_Username}`}>
I s there a reason fir this change?

2021-07-19 14:04 UTC, roddy3 commented on src/views/InvolvementProfile/components/Membership/components/MemberList/index.js
> +import MemberListItem from './components/MemberListSingle';
Same here

2021-07-19 14:04 UTC, roddy3 commented on src/views/InvolvementProfile/components/Membership/components/MemberList/components/MemberListSingle/index.js
> +            <Link className="gc360-link" to={`/profile/${member.AD_Username}`}>
same here

2021-07-22 16:26 UTC, russtuck commented
@cpabbot I think the difference is that #1280 only provides links for advisors and leaders, but not regular members.  David, is this right?

2021-07-22 16:34 UTC, closed without merging