S21 advanced search
gordon-cs/gordon-360-ui pull request #1259
Opened 2021-07-08 20:30 UTC by roddy3

Merged the three Dropdown Buttons into one Button that is called " Advanced Search" , Also added the Context sensitive fields.
------------
![Screen Shot 2021-07-08 at 4 20 13 PM](https://user-images.githubusercontent.com/60272749/124985729-bd95bf80-e008-11eb-9550-5812fa529714.png)

-----------
![Screen Shot 2021-07-08 at 4 20 28 PM](https://user-images.githubusercontent.com/60272749/124985769-cf776280-e008-11eb-8967-7101f491ece5.png)
-----------
![Screen Shot 2021-07-08 at 4 20 37 PM](https://user-images.githubusercontent.com/60272749/124985817-d9996100-e008-11eb-90ff-f0987f1c78ae.png)
-----------
![Screen Shot 2021-07-08 at 4 20 48 PM](https://user-images.githubusercontent.com/60272749/124985842-e322c900-e008-11eb-95d6-f8c0270398af.png)
-----------

After 

![Screen Shot 2021-07-08 at 4 24 47 PM](https://user-images.githubusercontent.com/60272749/124986160-52002200-e009-11eb-89bb-032d962a547f.png)
---------------

![Screen Shot 2021-07-08 at 4 25 20 PM](https://user-images.githubusercontent.com/60272749/124986218-617f6b00-e009-11eb-95ad-8807d282a3a7.png)
-------------

![Screen Shot 2021-07-08 at 4 25 35 PM](https://user-images.githubusercontent.com/60272749/124986272-70661d80-e009-11eb-85a8-9be17448141b.png)
------------

![Screen Shot 2021-07-08 at 4 25 45 PM](https://user-images.githubusercontent.com/60272749/124986305-7b20b280-e009-11eb-8d5f-43637951afe5.png)
-------------

![Screen Shot 2021-07-08 at 4 25 55 PM](https://user-images.githubusercontent.com/60272749/124986346-84aa1a80-e009-11eb-9076-60a19e129f84.png)
-----------

2021-07-08 20:31 UTC, EjPlatzer commented
Are we not able to search Alumni by major/minor/class?

2021-07-08 20:32 UTC, roddy3 commented
> Are we not able to search Alumni by major/minor/class?

2021-07-08 20:34 UTC, roddy3 commented
> Are we not able to search Alumni by major/minor/class?

2021-07-08 20:36 UTC, roddy3 commented
> Are we not able to search Alumni by major/minor/class?

-----

Alumni do not have majors because they already graduated as a result i do not think we can.

2021-07-09 14:16 UTC, roddy3 commented
> > > Are we not able to search Alumni by major/minor/class?
> 
> > 
> 
> > Alumni do not have majors because they already graduated as a result i do not think they are able to be searched by major/minor/class.
> 
> 
> 
> Recent Alumni actually do have majors, try searching for Addison Abbot.

I just realized that we never implemented searching Alumni by major/minor/class. That should be another project in the project board.

2021-07-09 14:51 UTC, iamphg97 commented
Great work. For consistency with checkboxes, Please change "Faculty & Staff" to "Faculty/Staff".

2021-07-09 16:05 UTC, Kevin-Chu58 commented
We are able to find alumni using the major filter, but we cannot find anyone alumni with the minor filter. That is because there are no columns for "major3" and "minor" in CCT.dbo.Alumni. We will ask Evan about this next week.
-------------------------------------------------------------------------------------------------------------------------------------------------
You probably want to enable the Major filter for alumni :)

2021-07-13 18:00 UTC, silasw2 requested changes
Some lines need to be removed instead of being commented out. Also, I would suggest adding a `disabled` color to the icons next to their fields if the field is disabled. This would make it much more clear to the user.

2021-07-13 18:59 UTC, roddy3 commented on src/views/PeopleSearch/index.js
> +      // offDepExpanded: !state.offDepExpanded,
@silasw2 done

2021-07-13 19:24 UTC, silasw2 submitted a review, later dismissed
LGTM! Looks real nice! Very clear!

2021-07-14 13:03 UTC, roddy3 commented on src/views/PeopleSearch/index.js
> +  handleAdvanceSearchExpandClick = () => {
Done!!!

2021-07-14 18:00 UTC, josh-peters-2357 requested changes

2021-07-14 18:00 UTC, josh-peters-2357 commented on src/views/PeopleSearch/index.js
> +        console.log(personType);
```suggestion
```

2021-07-14 19:23 UTC, josh-peters-2357 approved these changes

2021-07-14 20:40 UTC, roddy3 commented
> Will take more vertical space, but mobile view should probably stack inputs rather than squish them

what is the reason to stack them up @cpabbot ?

2021-07-16 13:06 UTC, Kevin-Chu58 reviewed
lgtm, probably

2021-07-16 15:30 UTC, roddy3 commented on src/views/PeopleSearch/index.js
> +                        backgroundColor="#ffffff"
We talked about it.

2021-07-16 15:30 UTC, roddy3 commented on src/views/PeopleSearch/index.js
> +                            <InputLabel id="demo-simple-select-filled-label">
done!!!

2021-07-16 15:32 UTC, merged