S21 Clifton Strengths 2.0
gordon-cs/gordon-360-ui pull request #1269
Opened 2021-07-13 13:58 UTC by cpabbot

## Clifton Strengths 2.0

![image](https://user-images.githubusercontent.com/17221652/125462176-e43b37fe-8c20-437a-acef-e48893dd473f.png)
![image](https://user-images.githubusercontent.com/17221652/125462207-14a7ac90-d1cc-4c45-b41b-aa756db300c4.png)
![image](https://user-images.githubusercontent.com/17221652/125462330-f3c6b0cd-7438-4f6f-bd97-2cf05bc188f5.png)
![image](https://user-images.githubusercontent.com/17221652/125462859-db733f0f-a1a0-4bda-8299-606a4152e483.png)

2021-07-13 14:28 UTC, ChrisImagineer commented
Wow! - Circle: that is super-clever and very design-sensitive. Subtle but purposeful. I think as long as its working well across user devices, then this is like a bonus design element, and a very well conceived one, too! Explanatory drop-down for the four domains: yes, that little feature that lists the domains with their colors is great.  It will be on our user experience team to create a corresponding outlink to a page that better describes the domains and CliftonStrengths itself. We can do that, and then add the outlink to this section later.  
 What does it look like on My Profile; which element is circled when two are displayed? I assume the Social photo, not the ID? Or what if there is only an ID photo? Just asking.

2021-07-13 15:17 UTC, ChrisImagineer commented
I think the gradient (however you've calculated that) is just great. I like it. It adds a visual curiosity that may lead to wondering why "some people have other colors than me?"  A feature like this can be an intentional way to draw a user to part of an experience you want them to notice or interact with more deeply, and so, why don't we go with that and see what it behavior it produces?

2021-07-13 18:03 UTC, josh-peters-2357 requested changes
This looks pretty cool. But one big problem I'm seeing with it is that it generates tons of warnings in console. Let's do it right and have no warnings, using best practices.

2021-07-13 18:03 UTC, josh-peters-2357 commented on src/services/user.js
> +        : null,
😮

2021-07-14 13:33 UTC, josh-peters-2357 submitted a review, later dismissed

2021-07-14 13:54 UTC, josh-peters-2357 approved these changes
lgtm

2021-07-14 14:03 UTC, merged