Data fetching all events from API
gordon-cs/gordon-360-ui pull request #1557
Opened 2022-11-06 03:18 UTC by silasw2

This is a PR for the working of both the Home page fetching all leagues and displaying their information, the activity page displaying all known info within itself, and the creation of a new league.

2022-11-09 18:21 UTC, silasw2 commented
This PR should be ready for merge. I would suggest checking it out and looking at the UI changes as well as the form to see if you have any comments.

2022-11-09 18:48 UTC, amos-cha requested changes
Minor changes then it should be good :)

2022-11-09 18:48 UTC, amos-cha commented on .env.development
> +REACT_APP_API_URL=http://localhost:51626/
Accidentally pushed env file?

2022-11-09 18:48 UTC, amos-cha commented on src/views/RecIM/components/CreateActivityForm/index.js
> +    console.log(activityCreationRequest);
```suggestion
```

2022-11-09 18:48 UTC, amos-cha commented on src/views/RecIM/components/CreateActivityForm/index.js
> +    let activityCreationRequest = { ...currentInfo, ...newInfo };
hot 🔥

2022-11-13 05:48 UTC, amos-cha approved these changes
Looks Good :)

2022-11-14 14:47 UTC, merged