Adds Clifton Strengths test link to profile if user has no strengths
gordon-cs/gordon-360-ui pull request #1671
Opened 2023-02-14 21:03 UTC by sofistonehouse

When the user has no Clifton Strengths, this will now display a link to the site where they can take the Clifton Strengths test.

2023-02-17 17:38 UTC, bennettforkner requested changes
Hi Sofi, this is looking good so far. I think there are still a few logic holes that we are missing, so I'm requesting changes.

2023-02-17 17:38 UTC, bennettforkner commented on src/components/Profile/components/PersonalInfoList/index.jsx
> +        profile.CliftonStrengths && (myProf || !profile.CliftonStrengths.Private) ? (
If you use the logic above, then you can also simplify this line to only check if they have clifton strengths:
```suggestion
        profile.CliftonStrengths ? (
```

2023-02-17 17:45 UTC, bennettforkner commented on src/components/Profile/components/PersonalInfoList/index.jsx
> +  const cliftonStrengths = (
If you choose to implement this change, I might put the `const showCliftonStrengthsBlock = ...` somewhere near the top of the component.

2023-02-20 02:50 UTC, sofistonehouse commented on .env.production
> + VITE_ANALYTICS_ID=UA-3559968-3
```suggestion
# VITE_API_URL=https://360Api1.gordon.edu/
# VITE_ANALYTICS_ID=UA-3559968-3
```

2023-02-20 02:50 UTC, sofistonehouse commented on .env.production
> +# VITE_API_URL=https://360ApiTrain.gordon.edu/
```suggestion
 VITE_API_URL=https://360ApiTrain.gordon.edu/
```

2023-02-20 02:52 UTC, sofistonehouse commented on src/components/Profile/components/PersonalInfoList/index.jsx
> +import { FaLessThanEqual } from 'react-icons/fa';
```suggestion
```

2023-02-21 20:28 UTC, bennettforkner commented on .env.production
> + VITE_API_URL=https://360ApiTrain.gordon.edu/
```suggestion
VITE_API_URL=https://360ApiTrain.gordon.edu/
```

2023-02-22 14:32 UTC, bennettforkner approved these changes
LGTM! Feel free to merge into develop when you are ready.

2023-02-22 22:29 UTC, bennettforkner approved these changes
Looks good to me! Ready for merge into develop branch.

2023-02-23 00:26 UTC, merged