[Rec-IM] Bracket UI
gordon-cs/gordon-360-ui pull request #1744
Opened 2023-03-26 17:29 UTC by cpabbot

## Rec-IM Bracket UI

2023-04-08 02:30 UTC, amos-cha commented on src/views/RecIM/components/RecimBracket/index.tsx
> +export default RecimBracket;
```suggestion
const RecIMBracket = () => {
  return <Bracket rounds={rounds} />;
};

export default RecIMBracket;
```

Sorry this is going to annoy me

2023-04-12 16:35 UTC, amos-cha requested changes
Couple of things to remove, the logic seems good but I wonder if there is a way to make it more readable. Though, it shouldn't be an issue we can't fix later down the road.

2023-04-12 16:35 UTC, amos-cha commented on src/views/RecIM/components/RecIMBracket/index.tsx
> +// import { Match } from 'services/recim/match';
```suggestion
```
unused import?

2023-04-12 16:35 UTC, amos-cha commented on src/views/RecIM/components/RecIMBracket/index.tsx
> +          // console.log('round:', index, roundNum, dataRounds[roundNum]);
```suggestion

      setRounds(
        Object.keys(dataRounds).map((index) => {
          let roundNum = parseInt(index);
```

2023-04-14 03:20 UTC, amos-cha approved these changes
Looks good, just got a single question? I'll ask on Teams and I'll just approve for now. It seems to work as intended.

2023-04-14 03:20 UTC, amos-cha commented on src/views/RecIM/components/RecIMBracket/index.tsx
> +                id: match.MatchID ?? Math.random(),
Doesn't `Math.random()` return a float between `0 & 1`

2023-04-16 17:38 UTC, amos-cha approved these changes
Solid changes!

2023-04-16 17:38 UTC, amos-cha commented on src/views/RecIM/components/RecIMBracket/index.tsx
>                  date: match.StartTime ? standardDate(match.StartTime, true) : '',
Good change! 👍🏼

2023-04-16 19:11 UTC, silasw2 approved these changes
I took a look and it looks great! Only thing I would mention is that you can click the "Show Bracket" switch sometimes even when there are no matches scheduled in that series. But otherwise awesome work!

2023-04-17 00:55 UTC, merged