Add a Mailto link in the search results page
gordon-cs/gordon-360-ui pull request #1774
Opened 2023-04-14 21:35 UTC by charlielee144r

Implements a use case where you can easily start emailing someone from the people search results list by adding a mailing icon/button for each result listed. 
This is only implemented in Desktop view for now because of the limited space for such a use case on a mobile view.

Fixes #1194

2023-04-30 02:50 UTC, charlielee144r commented
Here is what the current styling looks like:
![image](https://user-images.githubusercontent.com/24206170/235333136-2123533b-dd4a-4dc6-8e3d-29f2350ae876.png)

2023-04-30 03:00 UTC, bennettforkner commented
Hi @charlielee144r , looking good so far! On the design side, I would recommend giving a little bit more left & right padding to the button as well as decreasing the border-radius.

2023-05-02 20:38 UTC, charlielee144r commented
Current status of screen with all edits:
![image](https://user-images.githubusercontent.com/24206170/235780166-a03de6cb-f909-4358-a8e5-1a201be7d569.png)

2023-05-03 12:05 UTC, bennettforkner requested changes
Good job on this Charlie, it's a great feature to add here.

I have a few small code quality suggestions in my comments.

2023-05-03 12:05 UTC, bennettforkner commented on src/views/PeopleSearch/components/PeopleSearchResult/index.tsx
> +  );
You can actually set this to null if it is mobile view. A nice shortcut for specifying "only show this thing if this other thing is true" is:
```suggestion
  const emailIcon = !isMobileView && (
    <div className={styles.mailingIconContainer}>
      <CardActionArea className={styles.mailCardAction}>
        <a href={`mailto:${person.Email}`}>
          <MailOutlineIcon
            sx={{
              color: gordonColors.neutral.grayShades[50],
              height: '100%',
              width: 40,
              borderRadius: 2,
            }}
          />
        </a>
      </CardActionArea>
    </div>
  );
```

2023-05-03 12:05 UTC, bennettforkner commented on src/views/PeopleSearch/components/PeopleSearchResult/PeopleSearchResult.module.scss
> +.resultContainer {
```suggestion
.result_container {
```
Also here (see below comment)

2023-05-04 13:33 UTC, bennettforkner approved these changes
LGTM!

2023-05-04 18:48 UTC, merged