[Rec-IM] more status options
gordon-cs/gordon-360-ui pull request #1819
Opened 2023-06-01 19:01 UTC by antoniavonto

Implemented the change status  drop down button in the admin view of participants
![image](https://github.com/gordon-cs/gordon-360-ui/assets/115328139/50d0fcf6-bca3-41b2-a949-326efb9bf956)

2023-06-02 02:35 UTC, bennettforkner commented
Hello @antoniavonto -- if you are proposing changes to the recim branch, please set that as the "base" for your pull request instead of develop. It should be a red flag that your PR has 230 commits that are to be added.

2023-06-02 13:01 UTC, amos-cha commented
> Hello @antoniavonto -- if you are proposing changes to the recim branch, please set that as the "base" for your pull request instead of develop. It should be a red flag that your PR has 230 commits that are to be added.

👍🏼

2023-06-05 12:37 UTC, amos-cha requested changes
Good work so far, it would be beneficial for us if you also uploaded a screenshot of what the change looks like! You can do this with a `ctrl + shift + s` and just paste in the text for github!

2023-06-05 12:37 UTC, amos-cha commented on .env.development
> +#VITE_API_URL=https://360apirecim.gordon.edu/
remember to revert your `.env` files

2023-06-05 12:37 UTC, amos-cha commented on src/views/RecIM/components/List/Listing/index.jsx
> +    //loadUserInfo();
```suggestion
```

2023-06-07 20:37 UTC, amos-cha requested changes

2023-07-18 16:52 UTC, closed without merging