Adding a extra links tab on the header
gordon-cs/gordon-360-ui pull request #1862
Opened 2023-06-12 21:21 UTC by mla04762

2023-06-13 12:46 UTC, mla04762 commented
I am currently trying different things to see what would be the best option for having an extra links tab/page. For the most recent commit, I got rid of the links tab from the profile drop down after moving all the links in there to the new extra links tab on the header. Having an extra tab on the header made the header look a bit crowded, so I moved the involvements page in the links tab (people thought that was the least visited tab).

2023-06-20 17:06 UTC, amos-cha commented
@mla04762  remember to handle your merge conflicts

2023-06-20 17:08 UTC, amos-cha requested changes

2023-06-20 17:08 UTC, amos-cha commented on .env.development
> + #VITE_API_URL=http://localhost:51634/
revert

2023-06-20 17:08 UTC, amos-cha commented on src/components/Profile/index.jsx
> +
remove if unused

2023-07-24 23:39 UTC, russtuck commented
I think this is probably obsoleted by more recent changes in the header, and an idea to allow choosing favorite tabs to show.  The issue this was responding to has been closed, so closing this, too.

2023-07-24 23:39 UTC, closed without merging