S23 schedule panel conversion
gordon-cs/gordon-360-ui pull request #1867
Opened 2023-06-14 17:58 UTC by andrew-wzj

2023-06-20 16:33 UTC, amos-cha requested changes

2023-06-20 16:33 UTC, amos-cha commented on src/services/schedulecontrol.ts
>  }
```suggestion
async function setScheduleDescription(description: string): Promise<void> =>
  await http.put('schedulecontrol/description/', description);

```

2023-06-20 16:33 UTC, amos-cha commented on src/components/Profile/components/SchedulePanel/index.jsx
> +                    </Grid> */}
Is there use for this commented out section?

2023-06-20 16:33 UTC, amos-cha commented on src/components/Profile/components/SchedulePanel/index.jsx
>    };
```suggestion
  const handleIsExpanded = () => 
    setIsExpanded((prevExpanded) => !prevExpanded);

```

2023-06-20 16:33 UTC, amos-cha commented on src/components/Profile/components/SchedulePanel/index.jsx
> +    setLoading(false);
```suggestion
    } catch (e) {

    }
    setLoading(false);
```

The first set loading is redundant

2023-06-23 19:15 UTC, mla04762 commented on src/components/Profile/components/SchedulePanel/index.jsx
> +  } else if (!props.myProf && !isFaculty) {
We deprecated this `else if` condition because we figured that letting other students see other student's profile note would not be useful.

2023-06-23 19:18 UTC, mla04762 commented on src/components/Profile/components/SchedulePanel/index.jsx
> +              aria-controls="panel1a-content"
When we looked into what this was, it seemed to be the default for the accordion. I don't know why they chose this specific name, but we decided to not touch this.

2023-06-23 19:19 UTC, mla04762 commented on src/components/Profile/components/SchedulePanel/index.jsx
> +      </>
This was actually an `else if` case where students could only see other student's profile note, but it was deprecated

2023-07-13 17:47 UTC, closed without merging