Minor Color Theme updates
gordon-cs/gordon-360-ui pull request #1869
Opened 2023-06-15 17:55 UTC by jhammond4

A lot of the changes here are small ones to make color calls more consistent and ensure they're in line with the future dark mode. Some parts in these were changed from specific hard-coded colors, some changes were made to make elements more consistent (for some reason, the headers on the help page are totally different than all other headers on the site-is there a reason for this?), and I made it so all the drop-down links are the same color (some were different because they open a pop-up rather than taking the user to a link-all of them look the same now).

2023-06-16 20:27 UTC, jhammond4 commented on src/views/Help/index.jsx
> +                //titleTypographyProps={{ variant: 'body1' }}
No, I'll remove them

2023-06-26 12:26 UTC, Centerville1 commented on src/components/Header/components/NavButtonsRightCorner/index.jsx
> +import { ModeSwitcher } from 'components/ThemeModeSwitcher';
Make sure to remove this before we merge, we don't want to leave the test button in!

2023-06-26 13:18 UTC, Centerville1 requested changes
Bunch of stuff, some questions on changes, and mostly just replacing style props with new CSS classes.  Let me know if you've got any questions.

2023-06-26 13:18 UTC, Centerville1 commented on src/views/PeopleSearch/components/PeopleSearchResult/PeopleSearchResult.module.scss
> +  background-color: var(--mui-palette-neutral-light);
ditto here and below

2023-06-26 13:18 UTC, Centerville1 commented on src/views/PeopleSearch/components/PeopleSearchResult/index.tsx
>              sx={{
We should probably replace this sx prop with a CSS class.

2023-06-26 13:18 UTC, Centerville1 commented on src/views/PeopleSearch/components/SearchFieldList/index.tsx
> +    <b style={{ color: 'var(--mui-palette-secondary-main)' }}> Gordon </b>
You should replace this style= with a CSS class.

2023-06-26 13:18 UTC, Centerville1 commented on src/views/PeopleSearch/components/SearchFieldList/index.tsx
> +    <Card style={{ padding: '1rem' }} className={styles.people_section}>
Maybe consider making this a different CSS class to add the padding.  That might be unnecessary, but you could accomplish this by making a people_section_alt using the &_alt notation in SCSS.

2023-06-26 13:18 UTC, Centerville1 commented on src/views/PeopleSearch/components/SearchFieldList/index.tsx
> +                <ExpandMore style={{ color: 'var(--mui-palette-neutral-contrastText)' }} />
The style prop should be replaced with a CSS class.

2023-06-26 13:18 UTC, Centerville1 commented on src/views/Timesheets/index.jsx
> +  }, [profile]);*/
This still applies, don't just leave this commented out.  Either revert it, or delete it entirely(unless there's some compelling reason to leave it commented out)

2023-06-26 13:18 UTC, Centerville1 commented on src/views/Timesheets/index.jsx
> +                        //color={'var(--mui-palette-primary-main)'}
Remove this comment if it's not needed.

2023-06-26 13:18 UTC, Centerville1 commented on src/views/Timesheets/index.jsx
> +                          color: 'var(--mui-palette-secondary-main)',
You should replace this style prop with a CSS class.

2023-06-26 14:53 UTC, jhammond4 commented on src/views/Timesheets/index.jsx
> +  }, [profile]);*/
this blocks me from accessing timesheets because of staff-I just forgot to add it back in again

2023-06-26 14:59 UTC, jhammond4 commented on src/components/Header/components/NavButtonsRightCorner/index.jsx
> +      color={'var(--mui-palette-primary-main)'}
I don't remember adding this, I'll still take it out-from what I can tell it doesn't change anything

2023-06-26 15:11 UTC, jhammond4 commented on src/views/Help/Help.module.scss
> +    color: var(--mui-palette-primary-main);
I think I just forgot to change it to what color I actually wanted- I'll fix that as well

2023-06-26 15:12 UTC, jhammond4 commented on src/views/Help/Help.module.scss
> +    color: var(--mui-palette-primary-main);
See note above

2023-06-27 13:02 UTC, Centerville1 approved these changes
lgtm!  Great work!

2023-06-27 13:37 UTC, merged