Mailbox instructions link
gordon-cs/gordon-360-ui pull request #1886
Opened 2023-06-20 20:19 UTC by ahwnsals1234

Added link of the instruction videos to the mailbox instructions referencing #1815

2023-06-21 20:31 UTC, amos-cha requested changes

2023-06-21 20:31 UTC, amos-cha commented on src/components/Profile/components/PersonalInfoList/index.jsx
> +                        }}
```suggestion
                        style={{
                          borderBottom: '1px solid currentColor',
                          textDecoration: 'none',
                          color: gordonColors.primary.blueShades.A700,
                          fontSize: '1.1rem',
                          fontWeight: 'bold',
                        }}
```

Is there specific reason you don't have your styling inside of a `css` file?

2023-06-21 20:31 UTC, amos-cha commented on src/components/Profile/components/PersonalInfoList/index.jsx
> +                      <Typography sx={{ fontSize: '0.9rem', fontWeight: 'bold' }}>
```suggestion
                      <Typography sx={{ fontSize: '0.9rem', fontWeight: 'bold' }}>
```

Typography definitely can have its style in css

2023-06-21 20:31 UTC, amos-cha commented on src/components/Profile/components/PersonalInfoList/index.jsx
> +                        }}
ditto
```suggestion
                        style={{
                          borderBottom: '1px solid currentColor',
                          textDecoration: 'none',
                          color: gordonColors.primary.blueShades.A700,
                          fontSize: '1.1rem',
                          fontWeight: 'bold',
                        }}
```

2023-06-21 20:31 UTC, amos-cha commented on src/components/Profile/components/PersonalInfoList/index.jsx
> +                      <Typography sx={{ fontSize: '0.9rem', fontWeight: 'bold' }}>
```suggestion
                      <Typography sx={{ fontSize: '0.9rem', fontWeight: 'bold' }}>
```

ditto

2023-06-21 20:31 UTC, amos-cha commented on src/components/Profile/components/PersonalInfoList/index.jsx
> +                        }}
```suggestion
                        style={{
                          borderBottom: '1px solid currentColor',
                          textDecoration: 'none',
                          color: gordonColors.primary.blueShades.A700,
                          fontSize: '1.1rem',
                          fontWeight: 'bold',
                        }}
```

ditto

2023-06-21 20:31 UTC, amos-cha commented on src/components/Profile/components/PersonalInfoList/index.jsx
> +                      <Typography sx={{ fontSize: '0.9rem', fontWeight: 'bold' }}>
```suggestion
                      <Typography sx={{ fontSize: '0.9rem', fontWeight: 'bold' }}>
```
ditto

2023-06-21 20:31 UTC, amos-cha commented on src/components/Profile/components/PersonalInfoList/index.jsx
> +  };
```suggestion
  const onClose = () => {
    setIsJoinDialogOpen(false);
  };
```

`onClose` is called only once. You should probably just set the state from the location directly

2023-07-03 18:01 UTC, ahwnsals1234 commented
@amos-cha Made all the fixes according to the review, would be appreciated if you can take another look.

2023-07-03 18:09 UTC, amos-cha approved these changes

2023-07-03 18:10 UTC, merged