continue project from MyProfile-Involvments-Clutter - resolved merge conflicts
gordon-cs/gordon-360-ui pull request #1918
Opened 2023-06-27 15:48 UTC by antoniavonto

Trying to continue the work from the pull request https://github.com/gordon-cs/gordon-360-ui/pull/1083

Most code was taken from that pull request, but some had to change because of merge conflicts. 

Though it would probably would have been better to merge develop to that pull request and resolve merge conflicts, I thought a new branch that I could add the code in logical order was easier for me to understand and make the necessary changes to solve the conflicts.

2023-06-27 16:09 UTC, antoniavonto commented
![image](https://github.com/gordon-cs/gordon-360-ui/assets/115328139/1c85e81e-91bb-46b5-903c-7130fb0b3e18)

2023-06-29 20:13 UTC, antoniavonto commented
@amos-cha

2023-06-29 20:18 UTC, amos-cha requested changes
small cleanup then you're ready

2023-06-29 20:18 UTC, amos-cha commented on src/components/Profile/components/MembershipsList/components/MembershipInfoCard/MembershipInfoCard.module.scss
> +@media (max-width: 700px) {
```suggestion
@media (max-width: $break-sm) {
```

2023-06-29 20:18 UTC, amos-cha commented on src/components/Profile/components/MembershipsList/components/MembershipInfoCard/index.jsx
> +          }}
```suggestion
          onChange={() => 
            toggleMembershipPrivacy(element);
          }
```

2023-06-29 20:18 UTC, amos-cha commented on src/services/membership.ts
> +  // StartDate: string;
```suggestion
  // Description: string;
  // EndDate: string;
  // FirstName: string;
  // GroupAdmin: boolean;
  // IDNumber: number;
  // LastName: string;
  // MembershipID: number;
  // Participation: Participation;
  // ParticipationDescription: ParticipationDesc;
  // Privacy: boolean | null;
  // SessionCode: string;
  // SessionDescription: string;
  // StartDate: string;
```

remove if unused

2023-06-29 21:10 UTC, amos-cha approved these changes

2023-06-29 21:15 UTC, amos-cha approved these changes

2023-06-29 21:15 UTC, merged