[COLOR] changed color styles to CSS for more files
gordon-cs/gordon-360-ui pull request #1922
Opened 2023-06-28 13:13 UTC by ahwnsals1234

2023-06-28 19:15 UTC, jsenning submitted a review, later dismissed
These look good to me.

2023-06-29 14:30 UTC, Centerville1 requested changes
lgtm so far!  We'll wait to merge this until we get our main PR merged to develop, so marking it for changes to prevent accidental merging.

2023-06-29 15:30 UTC, ahwnsals1234 commented
I deleted the OfflineBanner file from 'src/components/OfflineBanner' because considering that it was only being called from the file itself, I assumed it is obsolete.

2023-06-29 15:45 UTC, Centerville1 requested changes
Looks pretty good to me!  Just a couple changes and questions I had.

2023-06-29 15:45 UTC, Centerville1 commented on src/components/EventList/components/EventItem/EventItem.module.scss
> +  background-color: var(--mui-palette-primary-contrastText);
This should probably be neutral light, since it's a background color, and not text(I assume)

2023-06-29 15:45 UTC, Centerville1 commented on src/components/Profile/components/VictoryPromise/components/GraphDisplay.tsx
> +const colors = new Array<VictoryPromiseColor | '#dbdbda'>(4);
Since this color is used in two places, it might be better to save this color to a variable in this file and then use that, up to you though.

2023-06-29 15:45 UTC, Centerville1 commented on src/components/Profile/components/VictoryPromise/components/VictoryPromiseIcons.tsx
> +  const secondary = active ? '#ffffff' : '#CCCCCB';
Same thing here with the reused colors, if might be better to save the reused ones to a variable.

Also, just to double check, 'var(--mui-...)' inside quotes didn't work here, right?

2023-06-29 15:45 UTC, Centerville1 commented on src/components/Profile/components/VictoryPromise/components/VictoryPromiseIcons.tsx
> +type PrimaryColor = VictoryPromiseColor | '#014983';
I'm not convinced this is the same, since it was doing a typeof call before.  Could you tell what this was doing previously?

2023-06-30 15:56 UTC, Centerville1 reviewed
lpgtm imho tbh, I'll approve this once we get our main branch merged to develop

2023-06-30 19:42 UTC, Centerville1 approved these changes
Good to go

2023-06-30 20:06 UTC, Centerville1 approved these changes

2023-06-30 20:06 UTC, merged