logo updates for favicon and PWA
gordon-cs/gordon-360-ui pull request #1956
Opened 2023-07-05 15:00 UTC by ahwnsals1234

- Updated splash screens for all ios device sizes on the pwa, updated the android splash screen icon.
- Added a loading screen in index.html to replace the white loading page.

2023-07-11 18:43 UTC, Centerville1 requested changes
Not ready to merge, just ready for review!

2023-07-12 18:24 UTC, ahwnsals1234 commented
@russtuck @amos-cha Have committed all the major changes needed to test run the PWA, splash screens, and favicon. Please review.

2023-07-12 20:44 UTC, Centerville1 reviewed
Everything lgtm, let me know if there's any reviews/questions about the loader I made.

2023-07-12 20:44 UTC, Centerville1 commented on public/images/android-icon-512x512.png
This icon should probably be the new logo in blue with no background, since the splash screen on Android generates a background based on the background color in manifest.json

2023-07-13 15:47 UTC, russtuck approved these changes
LGTM

2023-07-13 15:55 UTC, merged