base for the editing mail stop on profile
gordon-cs/gordon-360-ui pull request #1993
Opened 2023-07-10 21:26 UTC by antoniavonto

Not working yet

2023-07-12 19:25 UTC, antoniavonto commented
I wonder if it would be best to remove the options that start with "Box", though there are only the box numbers that are related to fac/staff

2023-07-13 17:06 UTC, amos-cha approved these changes
lgtm

2023-07-14 15:21 UTC, amos-cha requested changes

2023-07-14 15:21 UTC, amos-cha commented on .env.development
> + VITE_API_URL=http://localhost:51634/
revert

2023-07-17 14:19 UTC, amos-cha submitted a review, later dismissed

2023-07-17 17:57 UTC, amos-cha approved these changes

2023-07-17 20:39 UTC, merged