S24 migrate components typescript pt2
gordon-cs/gordon-360-ui pull request #2318
Opened 2024-06-18 20:45 UTC by dli505

A continuation of https://github.com/gordon-cs/gordon-360-ui/pull/2290
**Changes made in PR:**
- finished migration of Components to Typescript
- files finished:
    - Header
    - Loader
    - Nav
    - NavButton
    - PaletteSwitcherDialog
    - PhotoCropper
    - Profile
    - Providers
    - PWAInstructions
    - Snackbar
    - SpreadsheetUploader

2024-07-10 15:09 UTC, EjPlatzer commented on src/components/Profile/components/PersonalInfoList/components/UpdatePhoneDialog/index.tsx
> +  (props: { onChange: ({}) => void; name?: string } & InputBaseComponentProps, ref) => {
This is an incorrect type for `onChange` - please specify the type more accurately.

2024-07-10 15:13 UTC, EjPlatzer commented on src/components/Snackbar/index.tsx
> +export type severityType = 'error' | 'info' | 'success' | 'warning';
We should use the `AlertColor` type provided by MUI instead.

2024-07-10 15:13 UTC, EjPlatzer commented on src/components/SpreadsheetUploader/index.tsx
> +const displayCell = (cellData: any) => {
Better to use `unknown` here:
```suggestion
const displayCell = (cellData: unknown) => {
```

2024-07-10 15:14 UTC, EjPlatzer commented on src/components/SpreadsheetUploader/index.tsx
> +  setOpen: ({}) => void;
Again, this is an inaccurate type for this callback function. Please correctly type the parameter.

2024-07-10 15:15 UTC, EjPlatzer commented on src/components/SpreadsheetUploader/index.tsx
> +        open={error ? true : false}
```suggestion
        open={Boolean(error)}
```

2024-07-10 15:27 UTC, dli505 commented on src/components/EventList/index.tsx
> +            : events.map((event) => <EventItem {...event} key={event.Event_ID} />)}
I think something might have gotten messed up when I was trying to resolve merge conflicts, thanks for catching it!

2024-07-10 15:35 UTC, dli505 commented on src/components/PWAInstructions/index.tsx
> +const PWAInstructions = (props: any) => {
That was my bad, I was using it as a placeholder and forgot to change it. What type should be passed in? I haven't been able to figure it out.

2024-07-10 15:47 UTC, EjPlatzer commented on src/components/PWAInstructions/index.tsx
> +const PWAInstructions = (props: any) => {
If we look at where it's used in [`GuestWelcome`](https://github.com/gordon-cs/gordon-360-ui/blob/8aee5804ed033c687e1b61a42fa20b2a629892d8/src/views/Home/components/GuestWelcome/index.jsx#L112), we can see the props that are passed in. The only tricky one is `deferredPWAPrompt`, which appears to be an instance of a [`BeforeInstallPromptEvent`](https://developer.mozilla.org/en-US/docs/Web/API/BeforeInstallPromptEvent).

2024-07-10 17:16 UTC, dli505 commented on src/components/PWAInstructions/index.tsx
> +const PWAInstructions = (props: any) => {
Should I type  `deferredPWAPrompt` as `typeof BeforeInstallPromptEvent` or something else?

2024-07-10 18:37 UTC, EjPlatzer commented on src/components/PWAInstructions/index.tsx
> +const PWAInstructions = (props: any) => {
It's type should be `BeforeInstallPromptEvent`, no `typeof` needed, I believe.

2024-07-10 20:36 UTC, EjPlatzer requested changes
Looking great! Just a few more things.

2024-07-10 20:36 UTC, EjPlatzer commented on src/components/GordonDialogBox/index.tsx
> +      buttonClicked!(event);
A better approach would be to only call the function if the `buttonClicked` prop is not undefined:
```suggestion
      buttonClicked &&
      event.key === 'Enter' &&
      event.currentTarget.classList.contains('MuiDialog-root')
    ) {
      buttonClicked(event);
```

2024-07-10 20:36 UTC, EjPlatzer commented on src/components/Loader/index.tsx
> +        <CircularProgress size={size} color={color as Props['color']} />
This looks like a regression. We shouldn't need to override the type checking for `color`.

2024-07-10 20:36 UTC, EjPlatzer commented on src/components/PWAInstructions/index.tsx
> +  deferredPWAPrompt: typeof BeforeInstallPromptEvent;
This is not actually the correct `BeforeInstallPromptEvent`. Apparently, that event is non-standard, only supported in Chrome, and so the type is not officially available anywhere. Here is a good guide on how to add it properly: https://stackoverflow.com/a/67171375

2024-07-10 20:36 UTC, EjPlatzer commented on src/components/PWAInstructions/index.tsx
> +const PWAInstructions = ({ open, handleDisplay, deferredPWAPrompt }: props) => {
Looks like you updated this to destructure `props`, but didn't update the code which is still trying to use the `props` object that doesn't exist anymore.

2024-07-10 20:36 UTC, EjPlatzer commented on src/components/PWAInstructions/index.tsx
> +type props = {
Type names should be PascalCase (i.e. start with an uppercase letter).
```suggestion
type Props = {
```

2024-07-11 14:08 UTC, EjPlatzer requested changes
This is coming along great! The only thing left is that there are build errors, which need to be addressed before we can merge.

Specifically, the following errors:
```
src/components/PhotoCropper/index.tsx(222,9): error TS2322: Type 'AlertColor | null' is not assignable to type '"error" | "info" | "success" | "warning"'.
  Type 'null' is not assignable to type '"error" | "info" | "success" | "warning"'.

src/components/Profile/components/MembershipsList/index.tsx(105,16): error TS2786: 'MembershipsList' cannot be used as a JSX component.
  Its return type 'Element | Element[]' is not a valid JSX element.
    Type 'Element[]' is missing the following properties from type 'ReactElement<any, any>': type, props, key

src/components/Profile/components/PersonalInfoList/components/UpdatePhoneDialog/index.tsx(94,51): error TS2353: Object literal may only specify known properties, and 'name' does not exist in type 'EventTarget'.

src/components/Profile/index.tsx(64,29): error TS2322: Type 'FacStaffProfileInfo' is not assignable to type '{ BuildingDescription: string; OnCampusDepartment: string; OnCampusRoom: string; OnCampusPhone: string; PersonType: string; office_hours: string; Mail_Location: string; Mail_Description: ReactElement<...>; }'.
  Types of property 'Mail_Description' are incompatible.
    Type 'string' is not assignable to type 'ReactElement<any, string | JSXElementConstructor<any>>'.

src/views/CoCurricularTranscript/guestTranscript.tsx([18](https://github.com/gordon-cs/gordon-360-ui/actions/runs/9892608760/job/27325688832?pr=2318#step:6:19)0,3): error TS2561: Object literal may only specify known properties, but 'plannedGradYear' does not exist in type 'StudentProfileInfo'. Did you mean to write 'PlannedGradYear'?
```

2024-07-11 17:49 UTC, EjPlatzer approved these changes
LGTM!

2024-07-11 19:01 UTC, merged