Delete Button Finished (without confirmation pop-up)
gordon-cs/gordon-360-ui pull request #2413
Opened 2024-11-02 19:52 UTC by erandersen21

Sets an item's status to deleted and moves it to past reports, but does not include the confirmation pop-up. PR also contains status update front-end service.

2024-11-02 19:55 UTC, Luke-W-Hart approved these changes
LGTM! Watched as it worked.

2024-11-02 19:57 UTC, Centerville1 requested changes
LGTM too, but let's wait to merge until we add the pop-up confirmation modal.

2024-11-04 01:45 UTC, Luke-W-Hart requested changes

2024-11-04 01:45 UTC, Luke-W-Hart commented on src/views/CampusSafety/views/LostAndFound/index.tsx
> +    console.log(reportId);
Do we still need this console.log?
If so then LGTM, if not then it can be removed and that also LGTM!

2024-11-04 01:53 UTC, merged