wmr - Display On Duty Component Info
gordon-cs/gordon-360-ui pull request #2444
Opened 2024-11-27 23:42 UTC by jtasonye

**Changes made in PR:**
- Added API call to `RA_OnCall.ts` file to pull the On Duty RA's information
- Filled in the needed information for `On Duty` component (name, room #, contact info, photo, profile link)
- @Mrand03 or @dli505, one of you should test it to see if the information displays in your resident view. On the backend, the `Housing.Current_On_Call`, is the view that we pull from to display this information. Since my dorm (Wilson) does not have an RD (look at `RD_Info` view), the RA on duty for Wilson does not show up in the `Housing.Current_On_Call` view, so I cannot see whether it displays, but the logic to display it should be right
- This is a joint pull request with ________, so that needs to be approved before the results from this pull request can show up.

2024-11-29 02:34 UTC, dli505 commented on src/services/residentLife/RA_OnCall.ts
> +const fetchOnDutyRA = (hallId: string): Promise<RA[]> => http.get(`ra/on-call/${hallId}`);
This should be `Housing/ra/on-call/${hallId}`!

2024-11-29 02:34 UTC, dli505 requested changes
Hi Jason, great work here! Just a small bug fix where I commented and we should be good to go!

2024-11-30 05:20 UTC, jtasonye commented
Thanks for catching that @dli505 , I made the fix on the frontend and added some things and added some things in the backend so now it displays!

<img width="1440" alt="Screenshot 2024-11-30 at 12 11 02 AM" src="https://github.com/user-attachments/assets/5fd85a2a-31cd-433e-aeed-ae8209bd65b8">

2024-11-30 17:06 UTC, dli505 approved these changes
LGTM!

2024-12-02 16:17 UTC, merged